### PR TITLE
Correct Getting Started instructions

### PR DESCRIPTION
**Pull request by tennox**
https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux#22084103

### CODE REVIEW

**Comment by rolandschuetz** [comment]
Your proposed sed command returns on my Mac the following error:
_sed: RE error: illegal byte sequence_

Is this optimized for Windows or on which system is that working?

**Comment by tennox** [comment]
**sed --version**
> sed (GNU sed) 4.4
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by Jay Fenlason, Tom Lord, Ken Pizzini,
> and Paolo Bonzini.
> GNU sed home page: <http://www.gnu.org/software/sed/>.
> General help using GNU software: <http://www.gnu.org/gethelp/>.
> E-mail bug reports to: <bug-sed@gnu.org>.

`echo -e "1\n2\n3" > /tmp/f`
`sed -i='' 's/2/4/' /tmp/f` (works)
`sed -i'' 's/2/4/' /tmp/f` (works)
`sed -i '' 's/2/4/g' /tmp/f` - **sed: can't read s/2/4/g: No such file or directory**


Tested in bash and fish on elementary OS Hera (based on Ubuntu linux)

**Comment by rolandschuetz** [comment]
So my version would for on Mac OS and your's on linux? Could you extend the docu change to incorporate both versions?

**Comment by tennox** [comment]
Here's the underlying problem:
https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux#22084103

I'll update the docs

**Comment by rolandschuetz** [comment]
Great, thanks for the contribution!

**Pull request merged**
